### ISSUE TITLE
Would you like to register with AddonManger

### ISSUE THREAD

**Issue by writ312** [eunsoogi/tos-addons#77]
I saw the Readme
There are several wonderful Addon
I think that it is better if this can be installed from the manager
I am waiting for registration

**Comment by eunsoogi** [comment]
## 답변
OK. I'll clean up the ``addons.json`` and send pull request. But my addons need to some dependencies, so can I add ``dependencies`` to [addons.json](https://github.com/Tree-of-Savior-Addon-Community/Addons/blob/master/addons.json)?

## 참고할 문서
- https://github.com/Excrulon/Tree-of-Savior-Addon-Manager#submitting-addons

**Comment by eunsoogi** [comment]
## Wait for merge PR
- https://github.com/Tree-of-Savior-Addon-Community/AC-Util/pull/1
- https://github.com/Tree-of-Savior-Addon-Community/AC-Util/pull/2

## PR waiting
- https://github.com/eunsoogi/Addons/tree/ktos
- https://github.com/eunsoogi/Tree-of-Savior-Addon-Manager/tree/ktos

**Comment by eunsoogi** [comment]
Done.
