### ISSUE TITLE
Can u add mouse mode support to Icewall maker?

### ISSUE THREAD

**Issue by LamexDeSajg** [eunsoogi/tos-addons#95]
all in the title

**Comment by eunsoogi** [comment]
Can not you press the shift key in mouse mode?

**Comment by eunsoogi** [comment]
I can't find detecting mouse mode selection. Save your icewall cell using keyboard plz...

**Comment by LamexDeSajg** [comment]
Yeah i saved my icewall with keyboard but after that it cant be recreated in mouse mode, because in mouse mode u pick next square with mouse, not with arrowkeys, so maybe u can add something like 

If (Icewall casted = true)
 then
 If (shift pressed = true)
   1) Change input to keyboard
   2) Build icewall
   3) Change input to mouse mode 
 return
return

There is hotkey changing input modes addon already. But it kills idea of fast casting icewall if u do it manually.

**Comment by eunsoogi** [comment]
I found that addon is not work in mouse mode. I'll fix it soon.
