### ISSUE TITLE
BossSpotter multilanguage doesnt work

### ISSUE THREAD

**Issue by LamexDeSajg** [eunsoogi/tos-addons#96]
It seems that api doesnt hook up. [https://i.imgur.com/tuMpsnN.png](url)

**Comment by LamexDeSajg** [comment]
Oh, im playing on iTOS so its english.

**Comment by l02zpx** [comment]
Doesn't work in twtos

**Comment by eunsoogi** [comment]
@l02zpx 
Do not comment in closed issue.
You can publish new issue if you have problem.
